// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

/// {@template assets_generator.ASSETS_JPG_ICON_BANNER_LOGIN_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/icon_banner_login.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_JPG_ICON_FACEID_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/icon_faceid.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_JPG_ICON_FINGERPRINT_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/icon_fingerprint.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_JPG_IMAGE_BANNER_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/image_banner.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_JPG_IMAGE_DEFAULT_JPG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/image_default.jpg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_JPG_IMG_CARD_CCCD_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/img_card_cccd.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_JPG_IMG_MAIL_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/jpg/img_mail.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_PNG_NFC_ANDROID_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/png/nfc_android.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_PNG_NFC_IOS_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/png/nfc_ios.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ERROR_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/error-svgrepo-com.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_IC_ERROR_SNACKBAR_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/ic_error_snackbar.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/ic_success_snackbar.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ACC_EKYC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_acc_ekyc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ADD_ITEM_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_add_item.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ADDRESS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_address.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_APPEAR_EYE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_appear_eye.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_AUTHENTICATION_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_authentication.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_await_ocr_data.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BACK_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_back.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_background_payment.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BANNER_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_banner_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BANNER_LOGIN_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_banner_login.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BELL_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_bell.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BIRTHDAY_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_birthday.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BORDER_QR_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_border_qr.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_border_top_left.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_border_top_left_cap.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BUTTON_QR_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_button_qr.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_BUTTON_RETAKE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_button_retake.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CALENDER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_calender.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CANCEL_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_cancel.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_cancel_authentication.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CANLENDAR_CARD_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_canlendar_card.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CARD_CCCD_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_card_cccd.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CARD_INFO_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_card_info.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CHECKMARK_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_checkmark.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CIRCLE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_circle.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CLIENT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_client.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CLOSE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_close.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_COMPANY_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_company.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CONTRACT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_contract.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_corner_left_down.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_corner_left_up.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_corner_right_down.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_corner_right_up.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_CREATE_FOLDER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_create_folder.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_DELETE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_delete.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_DIRECTION_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_direction.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_DONE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_done.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_EMAIL_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_email.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_email_support.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_BETWEEN_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_between.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_BLINK_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_blink.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_DOWN_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_down.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_LEFT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_left.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_RIGHT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_right.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_SMILE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_smile.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACE_UP_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_face_up.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FACEID_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_faceid.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FINGERPRINT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_fingerprint.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FLASH_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_flash.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_FLASH_OFF_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_flash_off.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_GENDER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_gender.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_GLOBE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_globe.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HIDDEN_EYE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_hidden_eye.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_authentication.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_authentication_focus.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_FOCUS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_focus.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_LIST_USER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_list_user.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_list_user_focus.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_OTHER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_other.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_service_package.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_home_service_package_focus.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_HOTLINE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_hotline.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_instruct_live_ness.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_buy_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_extend_home_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_info_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_KYC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_kyc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_mission_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_item_recall_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_KYC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_kyc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_KYC_LOGIN_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_kyc_login.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_KYC_SMALL_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_kyc_small.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIST_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_list.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIST_CTS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_list_cts.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_list_document_item_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_list_document_not_confirm_item_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIST_NULL_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_list_null.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIST_USER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_list_user.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LIVE_NESS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_live_ness.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LOAD_ERR_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_load_err.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LOCK_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_lock.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LOGO_SUPPORT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_logo_support.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_LOGOUT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_logout.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_MAP_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_map.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_MORE_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_more_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NATIONALITY_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_nationality.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NFC_CONNECT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_nfc_connect.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_nfc_home_town.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_nfc_identifying_signs.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NFC_NATION_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_nfc_nation.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_no_support_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NOTI_BELL_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_noti_bell.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NOTI_SUCCESS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_noti_success.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NOTIFICATION_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_notification.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_notification_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_notification_home_focus.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_NUMBER_PHONE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_number_phone.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_OTHER_USER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_other_user.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_PACKAGE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_package.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_PACKAGE_CARD_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_package_card.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_PASS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_pass.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_REGISTER_KYC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_register_kyc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SCAN_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_scan_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SEARCH_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_search.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SERVICE_CA_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_service_ca.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_service_package.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SUCCESS_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_success.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SUPPORT_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_support.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_SUPPORT_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_support_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_TAG_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_tag.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_TAKE_PICTURE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_take_picture.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_TELEPHONE_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_telephone.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_USER_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_user.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_USER_NAME_CARD_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_user_name_card.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_WARNING_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_warning.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_ICON_WEB_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/icon_web.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/notification-13-svgrepo-com.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/success-standard-svgrepo-com.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_SVG_WARNING_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\package\package_ekyc\assets/svg/warning-svgrepo-com.svg)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}