// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'package_ekyc';

  static bool isFromModules = false;

  /// {@macro assets_generator.ASSETS_JPG_ICON_BANNER_LOGIN_PNG.preview}
  static String get ASSETS_JPG_ICON_BANNER_LOGIN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/icon_banner_login.png';

  /// {@macro assets_generator.ASSETS_JPG_ICON_FACEID_PNG.preview}
  static String get ASSETS_JPG_ICON_FACEID_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/icon_faceid.png';

  /// {@macro assets_generator.ASSETS_JPG_ICON_FINGERPRINT_PNG.preview}
  static String get ASSETS_JPG_ICON_FINGERPRINT_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/icon_fingerprint.png';

  /// {@macro assets_generator.ASSETS_JPG_IMAGE_BANNER_PNG.preview}
  static String get ASSETS_JPG_IMAGE_BANNER_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/image_banner.png';

  /// {@macro assets_generator.ASSETS_JPG_IMAGE_DEFAULT_JPG.preview}
  static String get ASSETS_JPG_IMAGE_DEFAULT_JPG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/image_default.jpg';

  /// {@macro assets_generator.ASSETS_JPG_IMG_CARD_CCCD_PNG.preview}
  static String get ASSETS_JPG_IMG_CARD_CCCD_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/img_card_cccd.png';

  /// {@macro assets_generator.ASSETS_JPG_IMG_MAIL_PNG.preview}
  static String get ASSETS_JPG_IMG_MAIL_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/jpg/img_mail.png';

  static String get ASSETS_LOCALES_VI_VN_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/vi_VN.json';

  /// {@macro assets_generator.ASSETS_PNG_NFC_ANDROID_PNG.preview}
  static String get ASSETS_PNG_NFC_ANDROID_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/png/nfc_android.png';

  /// {@macro assets_generator.ASSETS_PNG_NFC_IOS_PNG.preview}
  static String get ASSETS_PNG_NFC_IOS_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/png/nfc_ios.png';

  /// {@macro assets_generator.ASSETS_SVG_ERROR_SVGREPO_COM_SVG.preview}
  static String get ASSETS_SVG_ERROR_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/error-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_SVG_IC_ERROR_SNACKBAR_SVG.preview}
  static String get ASSETS_SVG_IC_ERROR_SNACKBAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/ic_error_snackbar.svg';

  /// {@macro assets_generator.ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
  static String get ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/ic_success_snackbar.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ACC_EKYC_SVG.preview}
  static String get ASSETS_SVG_ICON_ACC_EKYC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_acc_ekyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ADD_ITEM_SVG.preview}
  static String get ASSETS_SVG_ICON_ADD_ITEM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_add_item.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ADDRESS_SVG.preview}
  static String get ASSETS_SVG_ICON_ADDRESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_address.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_APPEAR_EYE_SVG.preview}
  static String get ASSETS_SVG_ICON_APPEAR_EYE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_appear_eye.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_AUTHENTICATION_SVG.preview}
  static String get ASSETS_SVG_ICON_AUTHENTICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_authentication.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG.preview}
  static String get ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_await_ocr_data.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BACK_SVG.preview}
  static String get ASSETS_SVG_ICON_BACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_back.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG.preview}
  static String get ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_background_payment.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BANNER_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_BANNER_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_banner_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BANNER_LOGIN_SVG.preview}
  static String get ASSETS_SVG_ICON_BANNER_LOGIN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_banner_login.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BELL_SVG.preview}
  static String get ASSETS_SVG_ICON_BELL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_bell.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BIRTHDAY_SVG.preview}
  static String get ASSETS_SVG_ICON_BIRTHDAY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_birthday.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_QR_SVG.preview}
  static String get ASSETS_SVG_ICON_BORDER_QR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_border_qr.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG.preview}
  static String get ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_border_top_left.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG.preview}
  static String get ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_border_top_left_cap.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BUTTON_QR_SVG.preview}
  static String get ASSETS_SVG_ICON_BUTTON_QR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_button_qr.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BUTTON_RETAKE_SVG.preview}
  static String get ASSETS_SVG_ICON_BUTTON_RETAKE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_button_retake.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CALENDER_SVG.preview}
  static String get ASSETS_SVG_ICON_CALENDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_calender.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANCEL_SVG.preview}
  static String get ASSETS_SVG_ICON_CANCEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_cancel.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
  static String get ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_cancel_authentication.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANLENDAR_CARD_SVG.preview}
  static String get ASSETS_SVG_ICON_CANLENDAR_CARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_canlendar_card.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CARD_CCCD_SVG.preview}
  static String get ASSETS_SVG_ICON_CARD_CCCD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_card_cccd.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CARD_INFO_SVG.preview}
  static String get ASSETS_SVG_ICON_CARD_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_card_info.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CHECKMARK_SVG.preview}
  static String get ASSETS_SVG_ICON_CHECKMARK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_checkmark.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CIRCLE_SVG.preview}
  static String get ASSETS_SVG_ICON_CIRCLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_circle.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CLIENT_SVG.preview}
  static String get ASSETS_SVG_ICON_CLIENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_client.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CLOSE_SVG.preview}
  static String get ASSETS_SVG_ICON_CLOSE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_close.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_COMPANY_SVG.preview}
  static String get ASSETS_SVG_ICON_COMPANY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_company.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CONTRACT_SVG.preview}
  static String get ASSETS_SVG_ICON_CONTRACT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_contract.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  static String get ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_corner_left_down.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG.preview}
  static String get ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_corner_left_up.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  static String get ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_corner_right_down.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG.preview}
  static String get ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_corner_right_up.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CREATE_FOLDER_SVG.preview}
  static String get ASSETS_SVG_ICON_CREATE_FOLDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_create_folder.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_DELETE_SVG.preview}
  static String get ASSETS_SVG_ICON_DELETE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_delete.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_DIRECTION_SVG.preview}
  static String get ASSETS_SVG_ICON_DIRECTION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_direction.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_DONE_SVG.preview}
  static String get ASSETS_SVG_ICON_DONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_done.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_EMAIL_SVG.preview}
  static String get ASSETS_SVG_ICON_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_email.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG.preview}
  static String get ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_email_support.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_BETWEEN_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_BETWEEN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_between.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_BLINK_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_BLINK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_blink.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_DOWN_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_DOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_down.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_LEFT_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_LEFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_left.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_RIGHT_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_RIGHT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_right.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_SMILE_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_SMILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_smile.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_UP_SVG.preview}
  static String get ASSETS_SVG_ICON_FACE_UP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_face_up.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACEID_SVG.preview}
  static String get ASSETS_SVG_ICON_FACEID_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_faceid.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FINGERPRINT_SVG.preview}
  static String get ASSETS_SVG_ICON_FINGERPRINT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_fingerprint.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FLASH_SVG.preview}
  static String get ASSETS_SVG_ICON_FLASH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_flash.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FLASH_OFF_SVG.preview}
  static String get ASSETS_SVG_ICON_FLASH_OFF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_flash_off.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_GENDER_SVG.preview}
  static String get ASSETS_SVG_ICON_GENDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_gender.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_GLOBE_SVG.preview}
  static String get ASSETS_SVG_ICON_GLOBE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_globe.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HIDDEN_EYE_SVG.preview}
  static String get ASSETS_SVG_ICON_HIDDEN_EYE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_hidden_eye.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_authentication.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_authentication_focus.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_FOCUS_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_FOCUS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_focus.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_LIST_USER_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_LIST_USER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_list_user.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_list_user_focus.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_OTHER_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_OTHER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_other.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_service_package.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG.preview}
  static String get ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_home_service_package_focus.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOTLINE_SVG.preview}
  static String get ASSETS_SVG_ICON_HOTLINE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_hotline.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG.preview}
  static String get ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_instruct_live_ness.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_buy_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_extend_home_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_info_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_KYC_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_KYC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_kyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_mission_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_item_recall_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_SVG.preview}
  static String get ASSETS_SVG_ICON_KYC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_kyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_LOGIN_SVG.preview}
  static String get ASSETS_SVG_ICON_KYC_LOGIN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_kyc_login.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_SMALL_SVG.preview}
  static String get ASSETS_SVG_ICON_KYC_SMALL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_kyc_small.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_SVG.preview}
  static String get ASSETS_SVG_ICON_LIST_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_list.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_CTS_SVG.preview}
  static String get ASSETS_SVG_ICON_LIST_CTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_list_cts.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_list_document_item_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_list_document_not_confirm_item_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_NULL_SVG.preview}
  static String get ASSETS_SVG_ICON_LIST_NULL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_list_null.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_USER_SVG.preview}
  static String get ASSETS_SVG_ICON_LIST_USER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_list_user.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIVE_NESS_SVG.preview}
  static String get ASSETS_SVG_ICON_LIVE_NESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_live_ness.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOAD_ERR_SVG.preview}
  static String get ASSETS_SVG_ICON_LOAD_ERR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_load_err.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOCK_SVG.preview}
  static String get ASSETS_SVG_ICON_LOCK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_lock.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOGO_SUPPORT_SVG.preview}
  static String get ASSETS_SVG_ICON_LOGO_SUPPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_logo_support.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOGOUT_SVG.preview}
  static String get ASSETS_SVG_ICON_LOGOUT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_logout.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_MAP_SVG.preview}
  static String get ASSETS_SVG_ICON_MAP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_map.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_MORE_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_MORE_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_more_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NATIONALITY_SVG.preview}
  static String get ASSETS_SVG_ICON_NATIONALITY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_nationality.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_SVG.preview}
  static String get ASSETS_SVG_ICON_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_CONNECT_SVG.preview}
  static String get ASSETS_SVG_ICON_NFC_CONNECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_nfc_connect.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG.preview}
  static String get ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_nfc_home_town.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
  static String get ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_nfc_identifying_signs.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_NATION_SVG.preview}
  static String get ASSETS_SVG_ICON_NFC_NATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_nfc_nation.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  static String get ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_no_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTI_BELL_SVG.preview}
  static String get ASSETS_SVG_ICON_NOTI_BELL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_noti_bell.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTI_SUCCESS_SVG.preview}
  static String get ASSETS_SVG_ICON_NOTI_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_noti_success.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_SVG.preview}
  static String get ASSETS_SVG_ICON_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_notification.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG.preview}
  static String get ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_notification_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG.preview}
  static String get ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_notification_home_focus.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NUMBER_PHONE_SVG.preview}
  static String get ASSETS_SVG_ICON_NUMBER_PHONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_number_phone.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_OTHER_USER_SVG.preview}
  static String get ASSETS_SVG_ICON_OTHER_USER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_other_user.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_PACKAGE_SVG.preview}
  static String get ASSETS_SVG_ICON_PACKAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_package.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_PACKAGE_CARD_SVG.preview}
  static String get ASSETS_SVG_ICON_PACKAGE_CARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_package_card.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_PASS_SVG.preview}
  static String get ASSETS_SVG_ICON_PASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_pass.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_REGISTER_KYC_SVG.preview}
  static String get ASSETS_SVG_ICON_REGISTER_KYC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_register_kyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SCAN_NFC_SVG.preview}
  static String get ASSETS_SVG_ICON_SCAN_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_scan_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SEARCH_SVG.preview}
  static String get ASSETS_SVG_ICON_SEARCH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_search.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SERVICE_CA_SVG.preview}
  static String get ASSETS_SVG_ICON_SERVICE_CA_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_service_ca.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG.preview}
  static String get ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_service_package.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUCCESS_SVG.preview}
  static String get ASSETS_SVG_ICON_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_success.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUPPORT_SVG.preview}
  static String get ASSETS_SVG_ICON_SUPPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_support.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUPPORT_NFC_SVG.preview}
  static String get ASSETS_SVG_ICON_SUPPORT_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_TAG_SVG.preview}
  static String get ASSETS_SVG_ICON_TAG_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_tag.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_TAKE_PICTURE_SVG.preview}
  static String get ASSETS_SVG_ICON_TAKE_PICTURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_take_picture.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_TELEPHONE_SVG.preview}
  static String get ASSETS_SVG_ICON_TELEPHONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_telephone.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_USER_SVG.preview}
  static String get ASSETS_SVG_ICON_USER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_user.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_USER_NAME_CARD_SVG.preview}
  static String get ASSETS_SVG_ICON_USER_NAME_CARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_user_name_card.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_WARNING_SVG.preview}
  static String get ASSETS_SVG_ICON_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_warning.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_WEB_SVG.preview}
  static String get ASSETS_SVG_ICON_WEB_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/icon_web.svg';

  /// {@macro assets_generator.ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
  static String get ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/notification-13-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
  static String get ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/success-standard-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_SVG_WARNING_SVGREPO_COM_SVG.preview}
  static String get ASSETS_SVG_WARNING_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/svg/warning-svgrepo-com.svg';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.ASSETS_JPG_ICON_BANNER_LOGIN_PNG.preview}
  Assets.ASSETS_JPG_ICON_BANNER_LOGIN_PNG,

  /// {@macro assets_generator.ASSETS_JPG_ICON_FACEID_PNG.preview}
  Assets.ASSETS_JPG_ICON_FACEID_PNG,

  /// {@macro assets_generator.ASSETS_JPG_ICON_FINGERPRINT_PNG.preview}
  Assets.ASSETS_JPG_ICON_FINGERPRINT_PNG,

  /// {@macro assets_generator.ASSETS_JPG_IMAGE_BANNER_PNG.preview}
  Assets.ASSETS_JPG_IMAGE_BANNER_PNG,

  /// {@macro assets_generator.ASSETS_JPG_IMAGE_DEFAULT_JPG.preview}
  Assets.ASSETS_JPG_IMAGE_DEFAULT_JPG,

  /// {@macro assets_generator.ASSETS_JPG_IMG_CARD_CCCD_PNG.preview}
  Assets.ASSETS_JPG_IMG_CARD_CCCD_PNG,

  /// {@macro assets_generator.ASSETS_JPG_IMG_MAIL_PNG.preview}
  Assets.ASSETS_JPG_IMG_MAIL_PNG,
  Assets.ASSETS_LOCALES_VI_VN_JSON,

  /// {@macro assets_generator.ASSETS_PNG_NFC_ANDROID_PNG.preview}
  Assets.ASSETS_PNG_NFC_ANDROID_PNG,

  /// {@macro assets_generator.ASSETS_PNG_NFC_IOS_PNG.preview}
  Assets.ASSETS_PNG_NFC_IOS_PNG,

  /// {@macro assets_generator.ASSETS_SVG_ERROR_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_SVG_ERROR_SVGREPO_COM_SVG,

  /// {@macro assets_generator.ASSETS_SVG_IC_ERROR_SNACKBAR_SVG.preview}
  Assets.ASSETS_SVG_IC_ERROR_SNACKBAR_SVG,

  /// {@macro assets_generator.ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
  Assets.ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ACC_EKYC_SVG.preview}
  Assets.ASSETS_SVG_ICON_ACC_EKYC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ADD_ITEM_SVG.preview}
  Assets.ASSETS_SVG_ICON_ADD_ITEM_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ADDRESS_SVG.preview}
  Assets.ASSETS_SVG_ICON_ADDRESS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_APPEAR_EYE_SVG.preview}
  Assets.ASSETS_SVG_ICON_APPEAR_EYE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_AUTHENTICATION_SVG.preview}
  Assets.ASSETS_SVG_ICON_AUTHENTICATION_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG.preview}
  Assets.ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BACK_SVG.preview}
  Assets.ASSETS_SVG_ICON_BACK_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG.preview}
  Assets.ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BANNER_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_BANNER_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BANNER_LOGIN_SVG.preview}
  Assets.ASSETS_SVG_ICON_BANNER_LOGIN_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BELL_SVG.preview}
  Assets.ASSETS_SVG_ICON_BELL_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BIRTHDAY_SVG.preview}
  Assets.ASSETS_SVG_ICON_BIRTHDAY_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_QR_SVG.preview}
  Assets.ASSETS_SVG_ICON_BORDER_QR_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG.preview}
  Assets.ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG.preview}
  Assets.ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BUTTON_QR_SVG.preview}
  Assets.ASSETS_SVG_ICON_BUTTON_QR_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_BUTTON_RETAKE_SVG.preview}
  Assets.ASSETS_SVG_ICON_BUTTON_RETAKE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CALENDER_SVG.preview}
  Assets.ASSETS_SVG_ICON_CALENDER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANCEL_SVG.preview}
  Assets.ASSETS_SVG_ICON_CANCEL_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
  Assets.ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANLENDAR_CARD_SVG.preview}
  Assets.ASSETS_SVG_ICON_CANLENDAR_CARD_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CARD_CCCD_SVG.preview}
  Assets.ASSETS_SVG_ICON_CARD_CCCD_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CARD_INFO_SVG.preview}
  Assets.ASSETS_SVG_ICON_CARD_INFO_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CHECKMARK_SVG.preview}
  Assets.ASSETS_SVG_ICON_CHECKMARK_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CIRCLE_SVG.preview}
  Assets.ASSETS_SVG_ICON_CIRCLE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CLIENT_SVG.preview}
  Assets.ASSETS_SVG_ICON_CLIENT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CLOSE_SVG.preview}
  Assets.ASSETS_SVG_ICON_CLOSE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_COMPANY_SVG.preview}
  Assets.ASSETS_SVG_ICON_COMPANY_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CONTRACT_SVG.preview}
  Assets.ASSETS_SVG_ICON_CONTRACT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  Assets.ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG.preview}
  Assets.ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  Assets.ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG.preview}
  Assets.ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_CREATE_FOLDER_SVG.preview}
  Assets.ASSETS_SVG_ICON_CREATE_FOLDER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_DELETE_SVG.preview}
  Assets.ASSETS_SVG_ICON_DELETE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_DIRECTION_SVG.preview}
  Assets.ASSETS_SVG_ICON_DIRECTION_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_DONE_SVG.preview}
  Assets.ASSETS_SVG_ICON_DONE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_EMAIL_SVG.preview}
  Assets.ASSETS_SVG_ICON_EMAIL_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG.preview}
  Assets.ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_BETWEEN_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_BETWEEN_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_BLINK_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_BLINK_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_DOWN_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_DOWN_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_LEFT_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_LEFT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_RIGHT_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_RIGHT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_SMILE_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_SMILE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_UP_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACE_UP_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACEID_SVG.preview}
  Assets.ASSETS_SVG_ICON_FACEID_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FINGERPRINT_SVG.preview}
  Assets.ASSETS_SVG_ICON_FINGERPRINT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FLASH_SVG.preview}
  Assets.ASSETS_SVG_ICON_FLASH_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_FLASH_OFF_SVG.preview}
  Assets.ASSETS_SVG_ICON_FLASH_OFF_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_GENDER_SVG.preview}
  Assets.ASSETS_SVG_ICON_GENDER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_GLOBE_SVG.preview}
  Assets.ASSETS_SVG_ICON_GLOBE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HIDDEN_EYE_SVG.preview}
  Assets.ASSETS_SVG_ICON_HIDDEN_EYE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_FOCUS_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_FOCUS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_LIST_USER_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_LIST_USER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_OTHER_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_OTHER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_HOTLINE_SVG.preview}
  Assets.ASSETS_SVG_ICON_HOTLINE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG.preview}
  Assets.ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_KYC_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_KYC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_SVG.preview}
  Assets.ASSETS_SVG_ICON_KYC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_LOGIN_SVG.preview}
  Assets.ASSETS_SVG_ICON_KYC_LOGIN_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_SMALL_SVG.preview}
  Assets.ASSETS_SVG_ICON_KYC_SMALL_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIST_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_CTS_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIST_CTS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_NULL_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIST_NULL_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_USER_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIST_USER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIVE_NESS_SVG.preview}
  Assets.ASSETS_SVG_ICON_LIVE_NESS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOAD_ERR_SVG.preview}
  Assets.ASSETS_SVG_ICON_LOAD_ERR_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOCK_SVG.preview}
  Assets.ASSETS_SVG_ICON_LOCK_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOGO_SUPPORT_SVG.preview}
  Assets.ASSETS_SVG_ICON_LOGO_SUPPORT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOGOUT_SVG.preview}
  Assets.ASSETS_SVG_ICON_LOGOUT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_MAP_SVG.preview}
  Assets.ASSETS_SVG_ICON_MAP_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_MORE_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_MORE_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NATIONALITY_SVG.preview}
  Assets.ASSETS_SVG_ICON_NATIONALITY_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_SVG.preview}
  Assets.ASSETS_SVG_ICON_NFC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_CONNECT_SVG.preview}
  Assets.ASSETS_SVG_ICON_NFC_CONNECT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG.preview}
  Assets.ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
  Assets.ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_NATION_SVG.preview}
  Assets.ASSETS_SVG_ICON_NFC_NATION_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  Assets.ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTI_BELL_SVG.preview}
  Assets.ASSETS_SVG_ICON_NOTI_BELL_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTI_SUCCESS_SVG.preview}
  Assets.ASSETS_SVG_ICON_NOTI_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_SVG.preview}
  Assets.ASSETS_SVG_ICON_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG.preview}
  Assets.ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG.preview}
  Assets.ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_NUMBER_PHONE_SVG.preview}
  Assets.ASSETS_SVG_ICON_NUMBER_PHONE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_OTHER_USER_SVG.preview}
  Assets.ASSETS_SVG_ICON_OTHER_USER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_PACKAGE_SVG.preview}
  Assets.ASSETS_SVG_ICON_PACKAGE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_PACKAGE_CARD_SVG.preview}
  Assets.ASSETS_SVG_ICON_PACKAGE_CARD_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_PASS_SVG.preview}
  Assets.ASSETS_SVG_ICON_PASS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_REGISTER_KYC_SVG.preview}
  Assets.ASSETS_SVG_ICON_REGISTER_KYC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SCAN_NFC_SVG.preview}
  Assets.ASSETS_SVG_ICON_SCAN_NFC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SEARCH_SVG.preview}
  Assets.ASSETS_SVG_ICON_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SERVICE_CA_SVG.preview}
  Assets.ASSETS_SVG_ICON_SERVICE_CA_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG.preview}
  Assets.ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUCCESS_SVG.preview}
  Assets.ASSETS_SVG_ICON_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUPPORT_SVG.preview}
  Assets.ASSETS_SVG_ICON_SUPPORT_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUPPORT_NFC_SVG.preview}
  Assets.ASSETS_SVG_ICON_SUPPORT_NFC_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_TAG_SVG.preview}
  Assets.ASSETS_SVG_ICON_TAG_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_TAKE_PICTURE_SVG.preview}
  Assets.ASSETS_SVG_ICON_TAKE_PICTURE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_TELEPHONE_SVG.preview}
  Assets.ASSETS_SVG_ICON_TELEPHONE_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_USER_SVG.preview}
  Assets.ASSETS_SVG_ICON_USER_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_USER_NAME_CARD_SVG.preview}
  Assets.ASSETS_SVG_ICON_USER_NAME_CARD_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_WARNING_SVG.preview}
  Assets.ASSETS_SVG_ICON_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_SVG_ICON_WEB_SVG.preview}
  Assets.ASSETS_SVG_ICON_WEB_SVG,

  /// {@macro assets_generator.ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG,

  /// {@macro assets_generator.ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG,

  /// {@macro assets_generator.ASSETS_SVG_WARNING_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_SVG_WARNING_SVGREPO_COM_SVG,
];
